api: 
  apikey: a4fd03f186d91d14d99417047e086696
  endpoint: "http://api.openweathermap.org/data/2.5/weather"
cache: 
  duration: 60s
database: 
  driver: redis
  host: redis_db
  port: 6379
server: 
  host: "http://localhost"
  port: 8000